package dev.ignotus.openbuds.integration.milink

object MilinkBridgeContract {
    const val ACTION_BIND = "dev.ignotus.openbuds.action.BIND_MILINK_BRIDGE"
    const val SERVICE_PACKAGE = "dev.ignotus.openbuds"
    const val SERVICE_CLASS = "dev.ignotus.openbuds.integration.milink.MilinkBridgeService"
    const val MILINK_PACKAGE = "com.milink.service"
    const val OPENBUDS_PACKAGE = "dev.ignotus.openbuds"

    const val KEY_TOKEN = "token"
    const val KEY_ENABLED = "enabled"
    const val KEY_CONNECTED = "connected"
    const val KEY_PROTOCOL_READY = "protocolReady"
    const val KEY_AUTHORIZED_MACS = "authorizedMacs"
    const val KEY_REASON = "reason"
    const val KEY_LAST_ERROR = "lastError"
    const val KEY_SUCCESS = "success"
    const val KEY_COMMAND_TYPE = "commandType"
    const val KEY_NOISE_MODE = "noiseMode"
    const val KEY_VOLUME = "volume"
    const val KEY_AUDIO_EFFECT_STATE = "audioEffectState"
    const val KEY_RING_ENABLED = "ringEnabled"
    const val KEY_REQUEST_ID = "requestId"

    const val KEY_MAC = "mac"
    const val KEY_NAME = "name"
    const val KEY_BRAND = "brand"
    const val KEY_MODEL = "model"
    const val KEY_DEVICE_ID = "deviceId"
    const val KEY_FORM_FACTOR = "formFactor"
    const val KEY_LEFT_BATTERY = "leftBattery"
    const val KEY_RIGHT_BATTERY = "rightBattery"
    const val KEY_CASE_BATTERY = "caseBattery"
    const val KEY_SINGLE_BATTERY = "singleBattery"
    const val KEY_LEFT_WEARING = "leftWearing"
    const val KEY_RIGHT_WEARING = "rightWearing"
    const val KEY_LEFT_CHARGING = "leftCharging"
    const val KEY_RIGHT_CHARGING = "rightCharging"
    const val KEY_CASE_CHARGING = "caseCharging"
    const val KEY_ANC_MODE = "ancMode"
    const val KEY_RINGING = "ringing"
    const val KEY_CURRENT_VOLUME = "currentVolume"
    const val KEY_CURRENT_AUDIO_EFFECT_STATE = "currentAudioEffectState"
    const val KEY_SUPPORTS_BATTERY = "supportsBattery"
    const val KEY_SUPPORTS_NOISE_CONTROL = "supportsNoiseControl"
    const val KEY_SUPPORTS_WEARING = "supportsWearing"
    const val KEY_SUPPORTS_RING = "supportsRing"
    const val KEY_SUPPORTS_VOLUME_CONTROL = "supportsVolumeControl"
    const val KEY_SUPPORTS_AUDIO_EFFECT = "supportsAudioEffect"
    const val KEY_SUPPORTS_EQ = "supportsEq"
    const val KEY_SUPPORTS_LEA_STATUS = "supportsLeaStatus"
    const val KEY_SUPPORTS_QUICK_ACCESS = "supportsQuickAccess"
    const val KEY_SUPPORTS_AMBIENT_LEVEL = "supportsAmbientLevel"
    const val KEY_REVISION = "revision"
    const val KEY_UPDATED_AT = "updatedAt"

    const val COMMAND_SET_NOISE_CONTROL = "set_noise_control"
    const val COMMAND_RING_FIND = "ring_find"
    const val COMMAND_START_RING = "start_ring"
    const val COMMAND_STOP_RING = "stop_ring"
    const val COMMAND_SET_VOLUME = "set_volume"
    const val COMMAND_SET_AUDIO_EFFECT = "set_audio_effect"
    const val COMMAND_PLAYBACK = "playback"
    const val COMMAND_SET_EQ_PRESET = "set_eq_preset"

    const val REASON_OK = "ok"
    const val REASON_DISABLED = "disabled"
    const val REASON_INVALID_COMMAND = "invalid_command"
    const val REASON_INVALID_MAC = "invalid_mac"
    const val REASON_INVALID_NOISE_MODE = "invalid_noise_mode"
    const val REASON_INVALID_VOLUME = "invalid_volume"
    const val REASON_INVALID_AUDIO_EFFECT = "invalid_audio_effect"
    const val REASON_NOT_CONNECTED = "not_connected"
    const val REASON_PROTOCOL_NOT_READY = "protocol_not_ready"
    const val REASON_UNAUTHORIZED_DEVICE = "unauthorized_device"
    const val REASON_UNSUPPORTED_CAPABILITY = "unsupported_capability"
    const val REASON_UNSUPPORTED_COMMAND = "unsupported_command"
    const val REASON_BRIDGE_UNAVAILABLE = "bridge_unavailable"
    const val REASON_TIMEOUT = "timeout"
    const val REASON_REMOTE_ERROR = "remote_error"
}
